user interface:
  theme: dark # dark or light
  themes:
  - name: dark
    back: 222
    font: ccc
  - name: light
    back: ccc
    font: 222

  # form fields
  form field notify display: no # or yes

  # beginners gui shows hints (e.g. call Mike)
  gui_for_beginners: yes

  default notify period: 1day # let's do it tomorrow

  # next event can be visible in main window
  show next event: yes # no when next event should not be visible
  show next range days: 3

  # if some event is notified, it could be reminded visually (notify-send on Linux)
  flashing reminder period seconds: 60
